# This is based on GitHub "Python Package using Anaconda"
on: [push, pull_request]

jobs:
  test:
    name: unittests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Unittest and Coverage
      run: |
        coverage run -m unittest && coverage report
      env:
        RNG_PLAYS: 100

    - name: Coveralls
      if: github.ref == 'refs/heads/master'
      uses: coverallsapp/github-action@v2

    - name: MypyCheck
      run: |
        mypy dgisim/ --check-untyped-defs
